name:                debruijn
version:             0.1.0.0
github:              ""
license:             BSD3
author:              "Florian Louvet"
maintainer:          "florian.louvet@epitech.eu"
copyright:           "2019 Florian Louvet"

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  deBruijn:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - debruijn

tests:
  deBruijn-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - debruijn
